Merge 4.4.23 into nougat-oos
d19e48f Linux 4.4.23
7b251d3 hostfs: Freeing an ERR_PTR in hostfs_fill_sb_common()
69b10e1 qxl: check for kmap failures
97f9aa7 power: supply: max17042_battery: fix model download bug.
a596ebc power_supply: tps65217-charger: fix missing platform_set_drvdata()
116fcd8 PM / hibernate: Fix rtree_next_node() to avoid walking off list ends
119c348 PM / hibernate: Restore processor state before using per-CPU variables
da40055 MIPS: paravirt: Fix undefined reference to smp_bootstrap
aebd335 MIPS: Add a missing ".set pop" in an early commit
49cded2 MIPS: Avoid a BUG warning during prctl(PR_SET_FP_MODE, ...)
9b30cac MIPS: Remove compact branch policy Kconfig entries
450abdd MIPS: vDSO: Fix Malta EVA mapping to vDSO page structs
b8a84b8 MIPS: SMP: Fix possibility of deadlock when bringing CPUs online
1872039 MIPS: Fix pre-r6 emulation FPU initialisation
05e5e96 i2c: qup: skip qup_i2c_suspend if the device is already runtime suspended
bbf1c4d i2c-eg20t: fix race between i2c init and interrupt enable
e944e69 btrfs: ensure that file descriptor used with subvol ioctls is a dir
f1b01a3 nl80211: validate number of probe response CSA counters
a68022d can: flexcan: fix resume function
7af3e4e mm: delete unnecessary and unsafe init_tlb_ubc()
8b275b4 tracing: Move mutex to protect against resetting of seq data
369796a fix memory leaks in tracing_buffers_splice_read()
3ee1b56 power: reset: hisi-reboot: Unmap region obtained by of_iomap
a52c63a mtd: pmcmsp-flash: Allocating too much in init_msp_flash()
4598783 mtd: maps: sa1100-flash: potential NULL dereference
3f5d832 fix fault_in_multipages_...() on architectures with no-op access_ok()
6e67de3 fanotify: fix list corruption in fanotify_get_response()
af426ec fsnotify: add a way to stop queueing events on group shutdown
fc4eddd xfs: prevent dropping ioend completions during buftarg wait
2ccb99b autofs: use dentry flags to block walks during expire
30b54a2 autofs races
9aea5e0 pwm: Mark all devices as "might sleep"
fd2e310 bridge: re-introduce 'fix parsing of MLDv2 reports'
8c945f5 net: smc91x: fix SMC accesses
339d61a Revert "phy: IRQ cannot be shared"
a3fb2b3 net: dsa: bcm_sf2: Fix race condition while unmasking interrupts
c03c024 net/mlx5: Added missing check of msg length in verifying its signature
4be4511 tipc: fix NULL pointer dereference in shutdown()
8d0d2ce net/irda: handle iriap_register_lsap() allocation failure
0bb225a vti: flush x-netns xfrm cache when vti interface is removed
9b5390d af_unix: split 'u->readlock' into two: 'iolock' and 'bindlock'
941f699 Revert "af_unix: Fix splice-bind deadlock"
f357a79 bonding: Fix bonding crash
56e5ad1 megaraid: fix null pointer check in megasas_detach_one().
e3718ed nouveau: fix nv40_perfctr_next() cleanup regression
2c4e9913 Staging: iio: adc: fix indent on break statement
682c360 iwlegacy: avoid warning about missing braces
1fff631 ath9k: fix misleading indentation
7fb33fb am437x-vfpe: fix typo in vpfe_get_app_input_index
c48692f Add braces to avoid "ambiguous ‘else’" compiler warnings
bc43ac8 net: caif: fix misleading indentation
a52031b Makefile: Mute warning for __builtin_return_address(>0) for tracing only
a521e94 Disable "frame-address" warning
3da2a4c Disable "maybe-uninitialized" warning globally
7cd4d22 gcov: disable -Wmaybe-uninitialized warning
6056237 Kbuild: disable 'maybe-uninitialized' warning for CONFIG_PROFILE_ALL_BRANCHES
d772ec1 kbuild: forbid kernel directory to contain spaces and colons
9b6bbc3 tools: Support relative directory path for 'O='
9728324 Makefile: revert "Makefile: Document ability to make file.lst and file.S" partially
252644d kbuild: Do not run modules_install and install in paralel
cf5fa7b ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
f1ce664 ocfs2/dlm: fix race between convert and migration
2426cdb crypto: echainiv - Replace chaining with multiplication
1c95a8a crypto: skcipher - Fix blkcipher walk OOM crash
9246fd2 crypto: arm/aes-ctr - fix NULL dereference in tail processing
3e2d986 crypto: arm64/aes-ctr - fix NULL dereference in tail processing
c867a11 tcp: properly scale window in tcp_v[46]_reqsk_send_ack()
0f55fa7 tcp: fix use after free in tcp_xmit_retransmit_queue()
9841855 tcp: cwnd does not increase in TCP YeAH
ea7dd21 ipv6: release dst in ping_v6_sendmsg
6b8076b ipv4: panic in leaf_walk_rcu due to stale node pointer
daef25a reiserfs: fix "new_insert_key may be used uninitialized ..."
29bd035 Fix build warning in kernel/cpuset.c
df12772 include/linux/kernel.h: change abs() macro so it uses consistent return type