Merge 4.4.22 into nougat-oos
8d5e93b Linux 4.4.22
7e30e5b openrisc: fix the fix of copy_from_user()
8519e28 avr32: fix 'undefined reference to `___copy_from_user'
005a463 ia64: copy_from_user() should zero the destination on access_ok() failure
2fbc61d genirq/msi: Fix broken debug output
735e76b ppc32: fix copy_from_user()
6de8178 sparc32: fix copy_from_user()
22782f0 mn10300: copy_from_user() should zero on access_ok() failure...
ba5bfcb nios2: copy_from_user() should zero the tail of destination
40c38ca openrisc: fix copy_from_user()
2558108 parisc: fix copy_from_user()
3123574 metag: copy_from_user() should zero the destination on access_ok() failure
0883ebb alpha: fix copy_from_user()
2e51ca2 asm-generic: make copy_from_user() zero the destination properly
8b3f6ed mips: copy_from_user() must zero the destination on access_ok() failure
0be8d73 hexagon: fix strncpy_from_user() error return
df243b4 sh: fix copy_from_user()
dd23e60 score: fix copy_from_user() and friends
0356e09 blackfin: fix copy_from_user()
012c06e cris: buggered copy_from_user/copy_to_user/clear_user
ad38170 frv: fix clear_user()
c6a4404 asm-generic: make get_user() clear the destination on errors
59a2d6b ARC: uaccess: get_user to zero out dest in cause of fault
bcc4b94 s390: get_user() should zero on failure
71cf375 score: fix __get_user/get_user
ba45b3f nios2: fix __get_user()
9ce4d2b sh64: failing __get_user() should zero
163a650 m32r: fix __get_user()
6eb02b0 mn10300: failing __get_user() and get_user() should zero
9d25c78 fix minor infoleak in get_user_ex()
a14f64c microblaze: fix copy_from_user()
51677e2 avr32: fix copy_from_user()
fdbeffb microblaze: fix __get_user()
9952691 fix iov_iter_fault_in_readable()
805f0c2 irqchip/atmel-aic: Fix potential deadlock in ->xlate()
17b54cc genirq: Provide irq_gc_{lock_irqsave,unlock_irqrestore}() helpers
e765e04 drm: Only use compat ioctl for addfb2 on X86/IA64
f487709 drm: atmel-hlcdc: Fix vertical scaling
b214985 net: simplify napi_synchronize() to avoid warnings
268a8bf kconfig: tinyconfig: provide whole choice blocks to avoid warnings
e50d38b soc: qcom/spm: shut up uninitialized variable warning
958acc3 pinctrl: at91-pio4: use %pr format string for resource
59e62eb mmc: dw_mmc: use resource_size_t to store physical address
0da2f82 drm/i915: Avoid pointer arithmetic in calculating plane surface offset
3314f1f mpssd: fix buffer overflow warning
0d284a3 gma500: remove annoying deprecation warning
8b18e0e ipv6: addrconf: fix dev refcont leak when DAD failed
a37a538 sched/core: Fix a race between try_to_wake_up() and a woken up task
7f71eec Revert "wext: Fix 32 bit iwpriv compatibility issue with 64 bit Kernel"
17127b7 ath9k: fix using sta->drv_priv before initializing it
10c2897 md-cluster: make md-cluster also can work when compiled into kernel
6267a54 xhci: fix null pointer dereference in stop command timeout function
8aa6a2a fuse: direct-io: don't dirty ITER_BVEC pages
5e0286e Btrfs: remove root_log_ctx from ctx list before btrfs_sync_log returns
3d1ca49 crypto: cryptd - initialize child shash_desc on import
554b0ee arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
c16cfc6 pinctrl: sunxi: fix uart1 CTS/RTS pins at PG on A23/A33
936a938 pinctrl: pistachio: fix mfio pll_lock pinmux
2ab3ad1 dm crypt: fix error with too large bios
3199308 dm log writes: move IO accounting earlier to fix error path
52fe288 dm log writes: fix check of kthread_run() return value
3c328c3 bus: arm-ccn: Fix XP watchpoint settings bitmask
bd47c36 bus: arm-ccn: Do not attempt to configure XPs for cycle counter
23d6ad9 bus: arm-ccn: Fix PMU handling of MN
e33981e ARM: dts: STiH407-family: Provide interconnect clock for consumption in ST SDHCI
ead4f54 ARM: dts: overo: fix gpmc nand on boards with ethernet
e2b1bd8 ARM: dts: overo: fix gpmc nand cs0 range
9c89714 ARM: dts: imx6qdl: Fix SPDIF regression
26dc6ac ARM: OMAP3: hwmod data: Add sysc information for DSI
d5d04f5 ARM: kirkwood: ib62x0: fix size of u-boot environment partition
c3aea8b ARM: imx6: add missing BM_CLPCR_BYPASS_PMIC_READY setting for imx6sx
11ba8bf ARM: imx6: add missing BM_CLPCR_BYP_MMDC_CH0_LPM_HS setting for imx6ul
e28b7b6 ARM: AM43XX: hwmod: Fix RSTST register offset for pruss
06ec7a1 cpuset: make sure new tasks conform to the current config of the cpuset
e43dcca net: thunderx: Fix OOPs with ethtool --register-dump
cfcbd5b USB: change bInterval default to 10 ms
15efc6e ARM: dts: STiH410: Handle interconnect clock required by EHCI/OHCI (USB)
34e255a6 usb: chipidea: udc: fix NULL ptr dereference in isr_setup_status_phase
59bc6b8 usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
b3e1877 USB: serial: simple: add support for another Infineon flashloader
58559c6 serial: 8250: added acces i/o products quad and octal serial cards
d5d1383 serial: 8250_mid: fix divide error bug if baud rate is 0
73c165a iio: ensure ret is initialized to zero before entering do loop
dd1e7b2 iio:core: fix IIO_VAL_FRACTIONAL sign handling
2157e33 iio: accel: kxsd9: Fix scaling bug
4b90e67 iio: fix pressure data output unit in hid-sensor-attributes
58ddc443 iio: accel: bmc150: reset chip at init time
8f1f9b0 iio: adc: at91: unbreak channel adc channel 3
734ee23 iio: ad799x: Fix buffered capture for ad7991/ad7995/ad7999
023e76b iio: adc: ti_am335x_adc: Increase timeout value waiting for ADC sample
a1f7219 iio: adc: ti_am335x_adc: Protect FIFO1 from concurrent access
5be0ba2 iio: adc: rockchip_saradc: reset saradc controller before programming it
cb082cd iio: proximity: as3935: set up buffer timestamps for non-zero values
3014185 iio: accel: kxsd9: Fix raw read return
1f72c8b kvm-arm: Unmap shadow pagetables properly
07450b3 x86/AMD: Apply erratum 665 on machines without a BIOS fix
7547bc9 x86/paravirt: Do not trace _paravirt_ident_*() functions
49bd6ae ARC: mm: fix build breakage with STRICT_MM_TYPECHECKS
abe5aab IB/uverbs: Fix race between uverbs_close and remove_one
00918ea dm flakey: fix reads to be issued if drop_writes configured
d0259cc audit: fix exe_file access in audit_exe_compare
f750847 mm: introduce get_task_exe_file
0d57cbc kexec: fix double-free when failing to relocate the purgatory
2f7e766 NFSv4.1: Fix the CREATE_SESSION slot number accounting
20e44c3 pNFS: Ensure LAYOUTGET and LAYOUTRETURN are properly serialised
1d13f37 nfsd: Close race between nfsd4_release_lockowner and nfsd4_lock
35c12ee NFSv4.x: Fix a refcount leak in nfs_callback_up_net
ab8cf65 pNFS: The client must not do I/O to the DS if it's lease has expired
a37004d kernfs: don't depend on d_find_any_alias() when generating notifications
2c6ae28 powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
76ddde6 powerpc/powernv : Drop reference added by kset_find_obj()
5354513 powerpc/tm: do not use r13 for tabort_syscall
e70bb22 tipc: move linearization of buffers to generic code
8e81d6b lightnvm: put bio before return
bf63b9d fscrypto: require write access to mount to set encryption policy
92c6786 Revert "KVM: x86: fix missed hardware breakpoints"
717cb2d MIPS: KVM: Check for pfn noslot case
5fa4220 clocksource/drivers/sun4i: Clear interrupts after stopping timer in probe function
8d693a2 fscrypto: add authorization check for setting encryption policy
d8aafd0 ext4: use __GFP_NOFAIL in ext4_free_blocks()

 Conflicts:
	arch/arm64/include/asm/spinlock.h
	arch/ia64/include/asm/uaccess.h
	arch/powerpc/include/asm/uaccess.h
	arch/sparc/include/asm/uaccess_32.h
	fs/f2fs/crypto_policy.c
	kernel/cpuset.c